model_name: "gpt-3.5-turbo"
#input_file: "tests/test.pdf"
input_file: "tests/The_Old_Man_of_the_Sea.pdf"
output_file_format: "markdown"
source_language: "English"
target_language: "Arabic"
api_key: "..."
base_url: "..."